import React, { useState, useMemo } from 'react';
import { ArrowLeft, ShoppingBag, X, Plus, Minus, CreditCard, ChevronRight, AlertCircle } from 'lucide-react';

// --- MOCK SHOPIFY DATA ---
const MOCK_PRODUCTS = [
  {
    id: 'prod_1',
    title: 'Saturday AM Official Logo Tee',
    price: 25.00,
    category: 'Apparel',
    image: 'https://pub-180171f859f64aa7aadb7001a6b96e65.r2.dev/homepage-graphic-assets/logos/SATURDAY%20AM%20Logo.png',
    description: 'Rep the world\'s most diverse manga anthology with our premium, ultra-soft cotton blend logo tee.',
    sizes: ['S', 'M', 'L', 'XL', '2XL']
  },
  {
    id: 'prod_2',
    title: 'Apple Black, Vol. 1',
    price: 14.99,
    category: 'Manga',
    image: 'https://pub-180171f859f64aa7aadb7001a6b96e65.r2.dev/assets/apple-black-cover.jpg',
    description: 'The critically acclaimed hit by Whyt Manga. Follow Sano as he strives to become the savior of Eden.',
    sizes: []
  },
  {
    id: 'prod_3',
    title: 'Clock Striker, Vol. 1',
    price: 14.99,
    category: 'Manga',
    image: 'https://pub-180171f859f64aa7aadb7001a6b96e65.r2.dev/assets/clock-striker-cover.jpg',
    description: 'Cast into a world of outlaws and machines, Cast must prove she has what it takes to be a Smith.',
    sizes: []
  },
  {
    id: 'prod_4',
    title: 'AM Crew Dad Hat',
    price: 30.00,
    category: 'Accessories',
    image: 'https://pub-180171f859f64aa7aadb7001a6b96e65.r2.dev/homepage-graphic-assets/logos/saturdayam%20LOGO%20cleaned%20ToBeVectored%20foot.png',
    description: 'Classic embroidered dad hat featuring the Saturday AM foot logo.',
    sizes: ['One Size']
  }
];

const CATEGORIES = ['All', 'Apparel', 'Manga', 'Accessories'];

export const Shop = ({ onBack, userTier }: any) => {
  const [activeCategory, setActiveCategory] = useState('All');
  const [cart, setCart] = useState<any[]>([]);
  const [isCartOpen, setIsCartOpen] = useState(false);
  const [selectedProduct, setSelectedProduct] = useState<any>(null);
  const [selectedSize, setSelectedSize] = useState('');

  const isSubscriber = userTier === 'premium';

  // Filter products based on active category
  const displayedProducts = useMemo(() => {
    if (activeCategory === 'All') return MOCK_PRODUCTS;
    return MOCK_PRODUCTS.filter(p => p.category === activeCategory);
  }, [activeCategory]);

  // Cart Calculations
  const cartSubtotal = cart.reduce((sum, item) => sum + (item.price * item.quantity), 0);
  const cartDiscount = isSubscriber ? cartSubtotal * 0.10 : 0; // 10% Pro discount!
  const cartTotal = cartSubtotal - cartDiscount;

  const handleAddToCart = (product: any, size: string) => {
    setCart(prev => {
      const existing = prev.find(item => item.id === product.id && item.size === size);
      if (existing) {
        return prev.map(item => 
          (item.id === product.id && item.size === size) 
            ? { ...item, quantity: item.quantity + 1 } 
            : item
        );
      }
      return [...prev, { ...product, size, quantity: 1 }];
    });
    setSelectedProduct(null);
    setSelectedSize('');
    setIsCartOpen(true);
  };

  const handleUpdateQuantity = (productId: string, size: string, delta: number) => {
    setCart(prev => prev.map(item => {
      if (item.id === productId && item.size === size) {
        const newQty = item.quantity + delta;
        return newQty > 0 ? { ...item, quantity: newQty } : item;
      }
      return item;
    }).filter(item => item.quantity > 0)); // Remove if quantity drops to 0
  };

  const handleMockCheckout = () => {
    alert("Shopify Integration Pending: This will redirect to the secure Shopify checkout URL generated by the Storefront API.");
  };

  return (
    <div className="min-h-screen bg-black text-white relative pb-24 font-sans">
      
      {/* GLOBAL BACKDROP */}
      <div className="fixed inset-0 z-[0] pointer-events-none">
        <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/carbon-fibre.png')] opacity-30 mix-blend-overlay" />
      </div>

      {/* HEADER */}
      <div className="sticky top-0 z-40 bg-black/90 backdrop-blur-xl px-4 pt-6 pb-4 border-b border-zinc-800 flex justify-between items-end">
        <div>
          <button onClick={onBack} className="mb-4 flex items-center gap-2 text-zinc-400 hover:text-white transition-colors">
            <ArrowLeft className="w-5 h-5" />
            <span className="text-[10px] font-black uppercase tracking-widest">Back</span>
          </button>
          <h1 className="text-3xl font-black italic uppercase tracking-tighter text-[#fe9a00] drop-shadow-md">
            AM Shop
          </h1>
        </div>

        <button 
          onClick={() => setIsCartOpen(true)}
          className="relative p-3 bg-zinc-900 border border-zinc-700 rounded-full hover:bg-zinc-800 transition-colors group mb-1"
        >
          <ShoppingBag className="w-6 h-6 text-white group-hover:text-[#fe9a00] transition-colors" />
          {cart.length > 0 && (
            <span className="absolute -top-1 -right-1 w-5 h-5 bg-[#fe9a00] text-black text-[10px] font-black rounded-full flex items-center justify-center animate-bounce shadow-md">
              {cart.reduce((sum, item) => sum + item.quantity, 0)}
            </span>
          )}
        </button>
      </div>

      {/* CATEGORY NAV */}
      <div className="relative z-10 w-full px-4 py-6 overflow-x-auto no-scrollbar border-b border-zinc-900 bg-black/50 backdrop-blur-sm">
        <div className="flex gap-3">
          {CATEGORIES.map(cat => (
            <button
              key={cat}
              onClick={() => setActiveCategory(cat)}
              className={`px-6 py-2.5 rounded-full font-black uppercase tracking-widest text-[10px] whitespace-nowrap transition-all ${
                activeCategory === cat 
                  ? 'bg-[#fe9a00] text-black shadow-[0_0_15px_rgba(254,154,0,0.4)]' 
                  : 'bg-zinc-900 text-zinc-400 border border-zinc-800 hover:text-white hover:border-zinc-600'
              }`}
            >
              {cat}
            </button>
          ))}
        </div>
      </div>

      {/* PRODUCT GRID */}
      <div className="relative z-10 max-w-7xl mx-auto px-4 py-8">
        <div className="grid grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 sm:gap-6">
          {displayedProducts.map(product => (
            <div 
              key={product.id} 
              className="bg-zinc-900 border border-zinc-800 rounded-2xl overflow-hidden group cursor-pointer hover:border-zinc-600 transition-all shadow-lg flex flex-col"
              onClick={() => setSelectedProduct(product)}
            >
              <div className="aspect-square bg-zinc-950 relative p-4 flex items-center justify-center overflow-hidden">
                <img 
                  src={product.image} 
                  alt={product.title} 
                  className="w-full h-full object-contain transform group-hover:scale-110 transition-transform duration-500 drop-shadow-2xl"
                />
                <div className="absolute inset-0 bg-black/50 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center backdrop-blur-sm">
                  <span className="bg-[#fe9a00] text-black font-black uppercase tracking-widest text-[10px] px-6 py-3 rounded-full shadow-xl">
                    Quick View
                  </span>
                </div>
              </div>
              <div className="p-4 flex flex-col flex-1">
                <p className="text-[9px] font-black uppercase tracking-widest text-zinc-500 mb-1">{product.category}</p>
                <h3 className="text-sm font-bold text-white mb-2 leading-snug line-clamp-2">{product.title}</h3>
                <div className="mt-auto flex items-center justify-between">
                  <span className="text-lg font-black italic text-[#fe9a00]">${product.price.toFixed(2)}</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* QUICK VIEW MODAL */}
      {selectedProduct && (
        <div className="fixed inset-0 z-[6000] bg-black/90 backdrop-blur-xl flex items-center justify-center p-4 sm:p-6 animate-fade-in" onClick={() => { setSelectedProduct(null); setSelectedSize(''); }}>
          <div className="w-full max-w-4xl bg-zinc-900 border border-zinc-800 rounded-3xl shadow-2xl overflow-hidden flex flex-col md:flex-row relative max-h-[90vh]" onClick={e => e.stopPropagation()}>
            
            <button onClick={() => { setSelectedProduct(null); setSelectedSize(''); }} className="absolute top-4 right-4 text-zinc-500 hover:text-white transition-colors z-20 bg-black/50 rounded-full p-2 backdrop-blur-md">
              <X className="w-5 h-5" />
            </button>

            {/* Modal Image */}
            <div className="md:w-1/2 bg-zinc-950 p-8 flex items-center justify-center relative">
              <div className="absolute inset-0 bg-gradient-to-t from-black via-transparent to-transparent opacity-50" />
              <img src={selectedProduct.image} alt={selectedProduct.title} className="w-full h-full object-contain relative z-10 drop-shadow-2xl" />
            </div>

            {/* Modal Details */}
            <div className="md:w-1/2 p-6 sm:p-10 overflow-y-auto custom-scrollbar flex flex-col">
              <p className="text-[10px] font-black uppercase tracking-widest text-[#fe9a00] mb-2">{selectedProduct.category}</p>
              <h2 className="text-2xl sm:text-3xl font-black italic uppercase tracking-tighter text-white mb-4 leading-tight">{selectedProduct.title}</h2>
              <span className="text-3xl font-black text-white mb-6">${selectedProduct.price.toFixed(2)}</span>
              
              <p className="text-sm text-zinc-400 font-bold leading-relaxed mb-8">
                {selectedProduct.description}
              </p>

              {selectedProduct.sizes && selectedProduct.sizes.length > 0 && (
                <div className="mb-8">
                  <div className="flex justify-between items-center mb-3">
                    <span className="text-xs font-black uppercase tracking-widest text-zinc-300">Select Size</span>
                  </div>
                  <div className="flex flex-wrap gap-3">
                    {selectedProduct.sizes.map((size: string) => (
                      <button
                        key={size}
                        onClick={() => setSelectedSize(size)}
                        className={`px-6 py-3 rounded-lg border-2 font-black text-xs uppercase tracking-wider transition-all ${
                          selectedSize === size 
                            ? 'border-[#fe9a00] bg-[#fe9a00]/10 text-[#fe9a00]' 
                            : 'border-zinc-800 bg-black text-zinc-400 hover:border-zinc-600 hover:text-white'
                        }`}
                      >
                        {size}
                      </button>
                    ))}
                  </div>
                </div>
              )}

              <button 
                disabled={selectedProduct.sizes.length > 0 && !selectedSize}
                onClick={() => handleAddToCart(selectedProduct, selectedSize)}
                className="mt-auto w-full py-4 bg-white text-black font-black uppercase tracking-widest rounded-xl hover:bg-[#fe9a00] transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                Add to Cart <ChevronRight className="w-4 h-4" />
              </button>
            </div>
          </div>
        </div>
      )}

      {/* SLIDE-OUT CART */}
      <div className={`fixed inset-0 z-[7000] transition-all duration-500 ${isCartOpen ? 'visible' : 'invisible'}`}>
        <div className={`absolute inset-0 bg-black/60 backdrop-blur-sm transition-opacity duration-500 ${isCartOpen ? 'opacity-100' : 'opacity-0'}`} onClick={() => setIsCartOpen(false)} />
        
        <div className={`absolute top-0 right-0 bottom-0 w-full sm:w-[450px] bg-zinc-950 border-l border-zinc-800 shadow-2xl flex flex-col transform transition-transform duration-500 ease-[cubic-bezier(0.16,1,0.3,1)] ${isCartOpen ? 'translate-x-0' : 'translate-x-full'}`}>
          
          {/* Cart Header */}
          <div className="flex justify-between items-center p-6 border-b border-zinc-800 bg-black">
            <h2 className="text-xl font-black italic uppercase text-white flex items-center gap-2">
              Your Cart 
              <span className="bg-[#fe9a00] text-black text-[10px] w-6 h-6 rounded-full flex items-center justify-center not-italic ml-2">
                {cart.reduce((sum, item) => sum + item.quantity, 0)}
              </span>
            </h2>
            <button onClick={() => setIsCartOpen(false)} className="text-zinc-500 hover:text-white p-2 rounded-full hover:bg-zinc-900 transition-colors">
              <X className="w-5 h-5" />
            </button>
          </div>

          {/* Cart Items */}
          <div className="flex-1 overflow-y-auto p-6 bg-zinc-950 custom-scrollbar">
            {cart.length === 0 ? (
              <div className="h-full flex flex-col items-center justify-center text-center opacity-50">
                <ShoppingBag className="w-16 h-16 text-zinc-600 mb-4" />
                <p className="text-sm font-black uppercase tracking-widest text-zinc-500">Your cart is empty</p>
              </div>
            ) : (
              <div className="space-y-6">
                {cart.map((item, index) => (
                  <div key={`${item.id}-${item.size}-${index}`} className="flex gap-4 bg-black border border-zinc-800 p-4 rounded-2xl">
                    <div className="w-20 h-20 bg-zinc-900 rounded-xl p-2 flex items-center justify-center flex-shrink-0">
                      <img src={item.image} alt={item.title} className="w-full h-full object-contain" />
                    </div>
                    <div className="flex flex-col flex-1">
                      <div className="flex justify-between items-start mb-1">
                        <h4 className="text-sm font-bold text-white leading-snug pr-4">{item.title}</h4>
                        <button onClick={() => handleUpdateQuantity(item.id, item.size, -item.quantity)} className="text-zinc-600 hover:text-red-500 transition-colors"><X className="w-4 h-4" /></button>
                      </div>
                      <p className="text-[10px] font-black uppercase tracking-widest text-zinc-500 mb-3">{item.size || 'Standard'}</p>
                      
                      <div className="mt-auto flex justify-between items-center">
                        <div className="flex items-center gap-3 bg-zinc-900 rounded-lg p-1 border border-zinc-800">
                          <button onClick={() => handleUpdateQuantity(item.id, item.size, -1)} className="p-1 text-zinc-400 hover:text-white"><Minus className="w-3 h-3" /></button>
                          <span className="text-xs font-black w-4 text-center">{item.quantity}</span>
                          <button onClick={() => handleUpdateQuantity(item.id, item.size, 1)} className="p-1 text-zinc-400 hover:text-white"><Plus className="w-3 h-3" /></button>
                        </div>
                        <span className="font-black italic text-[#fe9a00]">${(item.price * item.quantity).toFixed(2)}</span>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Cart Footer */}
          {cart.length > 0 && (
            <div className="border-t border-zinc-800 bg-black p-6 space-y-4">
              
              {isSubscriber && (
                <div className="flex items-start gap-3 bg-purple-900/20 border border-purple-500/30 p-3 rounded-xl">
                  <Crown className="w-5 h-5 text-purple-400 shrink-0" />
                  <div>
                    <p className="text-xs font-black uppercase tracking-widest text-purple-400 mb-0.5">AM+ Discount Applied</p>
                    <p className="text-[10px] text-purple-300/70 font-bold">You are saving 10% on your entire order today!</p>
                  </div>
                </div>
              )}

              <div className="space-y-2">
                <div className="flex justify-between items-center text-sm font-bold text-zinc-400">
                  <span>Subtotal</span>
                  <span>${cartSubtotal.toFixed(2)}</span>
                </div>
                {isSubscriber && (
                  <div className="flex justify-between items-center text-sm font-bold text-purple-400">
                    <span>Pro Discount (10%)</span>
                    <span>-${cartDiscount.toFixed(2)}</span>
                  </div>
                )}
                <div className="flex justify-between items-center text-lg font-black text-white pt-2 border-t border-zinc-800">
                  <span className="uppercase tracking-widest">Total</span>
                  <span>${cartTotal.toFixed(2)}</span>
                </div>
              </div>

              <button 
                onClick={handleMockCheckout}
                className="w-full py-4 bg-[#fe9a00] text-black font-black uppercase tracking-widest rounded-xl hover:bg-white transition-colors flex items-center justify-center gap-2 shadow-[0_0_20px_rgba(254,154,0,0.3)]"
              >
                Checkout <CreditCard className="w-4 h-4" />
              </button>
            </div>
          )}
        </div>
      </div>

    </div>
  );
};